# Generated by Django 5.1.2 on 2024-10-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('todoItem', models.CharField(max_length=50)),
                ('dateToComplete', models.DateField()),
            ],
        ),
    ]
