# Generated by Django 4.2.12 on 2024-10-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'Todo', 'verbose_name_plural': 'Todos'},
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='dateToComplete',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='todoItem',
            new_name='text',
        ),
        migrations.AddField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
